var owned = 'external chrome document i res basic r speechSynthesis caches localStorage sessionStorage webkitStorageInfo indexedDB webkitIndexedDB crypto applicationCache performance styleMedia defaultstatus defaultStatus screenTop screenLeft clientInformation console devicePixelRatio outerHeight outerWidth screenY screenX pageYOffset scrollY pageXOffset scrollX innerHeight innerWidth screen navigator frameElement parent opener top length frames closed status toolbar statusbar scrollbars personalbar menubar locationbar history location name self window ondeviceorientation ondevicemotion postMessage blur focus close onautocompleteerror onautocomplete onunload onstorage onpopstate onpageshow onpagehide ononline onoffline onmessage onlanguagechange onhashchange onbeforeunload onwaiting onvolumechange ontoggle ontimeupdate onsuspend onsubmit onstalled onshow onselect onseeking onseeked onscroll onresize onreset onratechange onprogress onplaying onplay onpause onmousewheel onmouseup onmouseover onmouseout onmousemove onmouseleave onmouseenter onmousedown onloadstart onloadedmetadata onloadeddata onload onkeyup onkeypress onkeydown oninvalid oninput onfocus onerror onended onemptied ondurationchange ondrop ondragstart ondragover ondragleave ondragenter ondragend ondrag ondblclick oncuechange oncontextmenu onclose onclick onchange oncanplaythrough oncanplay oncancel onblur onabort onwheel onwebkittransitionend onwebkitanimationstart onwebkitanimationiteration onwebkitanimationend ontransitionend onsearch onanimationstart onanimationiteration onanimationend stop open alert confirm prompt print requestAnimationFrame cancelAnimationFrame captureEvents releaseEvents getComputedStyle matchMedia moveTo moveBy resizeTo resizeBy getSelection find getMatchedCSSRules webkitRequestAnimationFrame webkitCancelAnimationFrame webkitCancelRequestAnimationFrame btoa atob setTimeout clearTimeout setInterval clearInterval scroll scrollTo scrollBy fetch TEMPORARY PERSISTENT webkitRequestFileSystem webkitResolveLocalFileSystemURL openDatabase addEventListener removeEventListener dispatchEvent';

var userDefined = [];
for ( var key in window ){
	if( owned.indexOf(key) === -1 && key !== 'userDefined' && key !== 'owned' ){
		userDefined.push(key);
	}
}
var res = userDefined.join(' ');
console.log(res);